//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.WebApi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bindopenidlog
    {
        public int Id { get; set; }
        public string bosscard { get; set; }
        public string name { get; set; }
        public string mobile { get; set; }
        public string isbind { get; set; }
        public string bindnum { get; set; }
        public string usercode { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string type { get; set; }
        public string hotelcode { get; set; }
        public string grouptype { get; set; }
        public string realbosscard { get; set; }
    }
}
