//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.WebApi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public int id { get; set; }
        public string category { get; set; }
        public string scene { get; set; }
        public Nullable<int> Invalid { get; set; }
        public Nullable<int> again { get; set; }
        public Nullable<int> sceneID { get; set; }
        public string hotelcode { get; set; }
        public Nullable<int> categoryId { get; set; }
    }
}
