//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.WebApi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_DCB
    {
        public int id { get; set; }
        public string hotelgroup { get; set; }
        public string tjcode { get; set; }
        public string address { get; set; }
        public string source { get; set; }
        public Nullable<decimal> totalscore { get; set; }
        public Nullable<decimal> greenscore { get; set; }
        public Nullable<decimal> ticketscore { get; set; }
        public Nullable<decimal> xfscore { get; set; }
        public string openid { get; set; }
        public string hy_name { get; set; }
        public string usertype { get; set; }
        public string cardtype { get; set; }
        public string realbosscard { get; set; }
        public string bosscard { get; set; }
        public string cardhotel { get; set; }
        public string nation { get; set; }
        public string country { get; set; }
        public string weixinnumber { get; set; }
        public string remark { get; set; }
        public string bosshk { get; set; }
        public string ratecode { get; set; }
        public string hy_kh { get; set; }
        public string hy_sex { get; set; }
        public string hy_zjlx { get; set; }
        public string hy_zjhm { get; set; }
        public string hy_jg { get; set; }
        public string hy_sr_m { get; set; }
        public string hy_sr_r { get; set; }
        public Nullable<int> hy_sr_nl { get; set; }
        public string hy_sjhm { get; set; }
        public string hy_dz_sf { get; set; }
        public string hy_dz_djs { get; set; }
        public string hy_dz_sx { get; set; }
        public string hy_dz_jd { get; set; }
        public string hy_yzbm { get; set; }
        public string hy_dcyq1 { get; set; }
        public string hy_dcyq_qt { get; set; }
        public string hy_cph { get; set; }
        public string hy_dw_name { get; set; }
        public string hy_dw_dz_sf { get; set; }
        public string hy_dw_dz_djs { get; set; }
        public string hy_dw_dz_sx { get; set; }
        public string hy_dw_dz_jd { get; set; }
        public string hy_dw_xz { get; set; }
        public string hy_dw_zw { get; set; }
        public string hy_lxdh { get; set; }
        public string hy_Email { get; set; }
        public string hy_qq_msn { get; set; }
        public string hy_zp_path { get; set; }
        public string hy_qmz_path { get; set; }
        public string hy_dcyq2 { get; set; }
        public string hy_dcyq3 { get; set; }
        public string hy_dcyq4 { get; set; }
        public string hy_wx { get; set; }
        public string hy_xyk { get; set; }
        public Nullable<decimal> hy_ljxf { get; set; }
        public Nullable<decimal> hy_mrhbj { get; set; }
        public Nullable<decimal> hy_mrhzs { get; set; }
        public string hy_jhtwo { get; set; }
        public string hy_jhthree { get; set; }
        public string hy_jhfour { get; set; }
        public string hy_jhsix { get; set; }
        public string hy_jhseven { get; set; }
        public string hy_jheight { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public Nullable<decimal> hy_bjye { get; set; }
        public Nullable<decimal> hy_zsye { get; set; }
        public Nullable<decimal> hy_mrhgme { get; set; }
        public string hy_jhone { get; set; }
        public string hy_jhfive { get; set; }
        public string hy_jhlv { get; set; }
        public string hy_jhsw { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string state { get; set; }
        public Nullable<System.DateTime> arr { get; set; }
        public string saleid { get; set; }
        public Nullable<System.DateTime> lasttime { get; set; }
        public Nullable<System.DateTime> lasttime1 { get; set; }
        public Nullable<decimal> bjye { get; set; }
        public Nullable<decimal> zqye { get; set; }
        public Nullable<decimal> jfye { get; set; }
    }
}
