//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.WebApi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FunctionManagement
    {
        public int id { get; set; }
        public Nullable<int> isSendWeather { get; set; }
        public Nullable<int> people { get; set; }
        public Nullable<int> Discounted { get; set; }
        public Nullable<int> payment { get; set; }
        public Nullable<int> register { get; set; }
        public Nullable<int> Shopping { get; set; }
        public string hotelcode { get; set; }
    }
}
