//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.WebApi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberBindInfo
    {
        public int id { get; set; }
        public string hy_sjhm { get; set; }
        public string hy_kh { get; set; }
        public string openid { get; set; }
        public string source { get; set; }
        public string tjcode { get; set; }
        public string hotelcode { get; set; }
    }
}
