//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.WebApi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemeberBalance
    {
        public int id { get; set; }
        public string bosscard { get; set; }
        public string name { get; set; }
        public string mobile { get; set; }
        public Nullable<decimal> tmoney { get; set; }
        public Nullable<decimal> tmoney_dj { get; set; }
        public Nullable<decimal> tmoney_xf { get; set; }
        public Nullable<decimal> tmoney_gq { get; set; }
        public Nullable<decimal> tmoney_kp { get; set; }
        public Nullable<int> yhqnum { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string hotelcode { get; set; }
        public string realbosscard { get; set; }
    }
}
