//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.WebApi.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MPDBEntities : DbContext
    {
        public MPDBEntities()
            : base("name=MPDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MemeberBalance> MemeberBalances { get; set; }
        public DbSet<MPConfig> MPConfigs { get; set; }
        public DbSet<HotelScene_t> HotelScene_t { get; set; }
        public DbSet<TicketExpire_t> TicketExpire_t { get; set; }
        public DbSet<PushMsgInfo> PushMsgInfoes { get; set; }
        public DbSet<PrintTicket> PrintTickets { get; set; }
    }
}
