//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.WebApi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shoppingurl
    {
        public int id { get; set; }
        public string url { get; set; }
        public string hotelcode { get; set; }
        public string remark { get; set; }
        public Nullable<int> flag { get; set; }
    }
}
