//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.WebApi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserScene
    {
        public int Id { get; set; }
        public string hotelcode { get; set; }
        public string hotelgroupcode { get; set; }
        public string usercode { get; set; }
        public string scene { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string name { get; set; }
        public string scenename { get; set; }
    }
}
