//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorizedLog_t
    {
        public int id { get; set; }
        public Nullable<int> formulaid { get; set; }
        public string hotelcode { get; set; }
        public string roomcode { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string mobile { get; set; }
        public string returncode { get; set; }
        public string tp_id { get; set; }
        public Nullable<int> status { get; set; }
        public string admin { get; set; }
        public string username { get; set; }
        public string cardno { get; set; }
        public string formulaname { get; set; }
        public string canceladmin { get; set; }
        public Nullable<System.DateTime> canceltime { get; set; }
    }
}
