//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_t
    {
        public int CategoryId { get; set; }
        public string hotelcode { get; set; }
        public string CategoryName { get; set; }
        public string CategoryNamebm { get; set; }
        public string Categorycode { get; set; }
        public string Summary { get; set; }
        public string HotelId { get; set; }
        public string pic { get; set; }
        public string BeginString { get; set; }
        public string EndString { get; set; }
        public Nullable<int> maxNum { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<int> sflag { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public Nullable<int> type { get; set; }
        public string ExpireDate { get; set; }
        public string ExpireDateend { get; set; }
        public Nullable<int> endnum { get; set; }
        public string dzpq { get; set; }
        public Nullable<int> isbool { get; set; }
        public Nullable<int> moneytype { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<decimal> fmoney { get; set; }
        public Nullable<int> iswxly { get; set; }
        public Nullable<int> fnum { get; set; }
        public Nullable<int> iszs { get; set; }
        public Nullable<int> iscz { get; set; }
        public Nullable<int> istest { get; set; }
        public string bgpic { get; set; }
    }
}
