//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAVRecord_t
    {
        public int id { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string addname { get; set; }
        public string categoryid { get; set; }
        public string deptcode { get; set; }
        public string fmoney { get; set; }
        public string FormulaId { get; set; }
        public string gdcode { get; set; }
        public string hotelcode { get; set; }
        public string hotelcodenew { get; set; }
        public string jycode { get; set; }
        public string no { get; set; }
        public string ticketsn { get; set; }
        public string tp_id { get; set; }
        public string tmoney { get; set; }
        public string usercode { get; set; }
        public Nullable<System.DateTime> userdate { get; set; }
        public string usertype { get; set; }
        public string xfcode { get; set; }
        public string xftype { get; set; }
        public string ts { get; set; }
        public string firstts { get; set; }
        public string sflag { get; set; }
        public string scene { get; set; }
        public string channel { get; set; }
        public string time { get; set; }
        public string mobile { get; set; }
        public string categoryname { get; set; }
        public string formulaname { get; set; }
        public string username { get; set; }
        public string bosscard { get; set; }
        public string realbosscard { get; set; }
        public Nullable<decimal> rate { get; set; }
    }
}
