//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbdata_t
    {
        public int id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> num { get; set; }
        public string oid { get; set; }
        public Nullable<int> dbnameid { get; set; }
        public string hotelcode { get; set; }
    }
}
