//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formula_t
    {
        public int FormulaId { get; set; }
        public string hotelcode { get; set; }
        public string FormulaName { get; set; }
        public string FormulaSummary { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<int> yztype { get; set; }
        public string Formulacode { get; set; }
        public Nullable<int> maxnum { get; set; }
        public Nullable<decimal> fmoney { get; set; }
        public Nullable<int> fnum { get; set; }
        public string img { get; set; }
        public string hotelcodenew { get; set; }
        public Nullable<int> isxg { get; set; }
    }
}
