//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class formula_authorized
    {
        public int id { get; set; }
        public Nullable<int> formulaid { get; set; }
        public string hotelcode { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string addname { get; set; }
        public string formulaname { get; set; }
    }
}
