//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formula_t
    {
        public int FormulaId { get; set; }
        public string hotelcode { get; set; }
        public string FormulaName { get; set; }
        public string FormulaSummary { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<int> yztype { get; set; }
        public string Formulacode { get; set; }
        public Nullable<int> maxnum { get; set; }
        public Nullable<decimal> fmoney { get; set; }
        public Nullable<int> fnum { get; set; }
        public string img { get; set; }
        public string hotelcodenew { get; set; }
        public Nullable<int> isxg { get; set; }
    }
}
