//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iticketDB : DbContext
    {
        public iticketDB()
            : base("name=iticketDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category_fw_t> Category_fw_t { get; set; }
        public DbSet<Category_t> Category_t { get; set; }
        public DbSet<CAVRecord_t> CAVRecord_t { get; set; }
        public DbSet<dbdata_t> dbdata_t { get; set; }
        public DbSet<dbname_t> dbname_t { get; set; }
        public DbSet<Formula_fw_t> Formula_fw_t { get; set; }
        public DbSet<Formula_t> Formula_t { get; set; }
    }
}
