//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iticketEntities : DbContext
    {
        public iticketEntities()
            : base("name=iticketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CAVRecord_t> CAVRecord_t { get; set; }
        public DbSet<Category_t> Category_t { get; set; }
        public DbSet<dbname_t> dbname_t { get; set; }
        public DbSet<Category_fw_t> Category_fw_t { get; set; }
        public DbSet<Formula_fw_t> Formula_fw_t { get; set; }
        public DbSet<dbdata_t> dbdata_t { get; set; }
        public DbSet<Formula_t> Formula_t { get; set; }
    }
}
