//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendTicketLog_Mall
    {
        public int id { get; set; }
        public string ordercode { get; set; }
        public string onsalecode { get; set; }
        public string ticketsn { get; set; }
        public string jgxz { get; set; }
        public string sysj { get; set; }
        public string mobile { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string hotelcode { get; set; }
        public string returncode { get; set; }
        public Nullable<int> type { get; set; }
        public string tp_id { get; set; }
    }
}
